

DROP TABLE IF EXISTS tickets CASCADE;
DROP TABLE IF EXISTS film_times CASCADE;
DROP TABLE IF EXISTS customers CASCADE;
DROP TABLE IF EXISTS films CASCADE;


CREATE TABLE customers(
  id SERIAL8 PRIMARY KEY,
  name VARCHAR(255),
  funds INT8
);

CREATE TABLE films(
  id SERIAL8 PRIMARY KEY,
  title VARCHAR(255),
  price INT8
);

CREATE TABLE film_times(
  id SERIAL8 PRIMARY KEY,
  film_id INT8 REFERENCES films(id) ON DELETE CASCADE,
  show_time TIME
);

CREATE TABLE tickets(
  id SERIAL8 PRIMARY KEY,
  customer_id INT8 REFERENCES customers(id) ON DELETE CASCADE,
  show_time_id INT8 REFERENCES film_times(id) ON DELETE CASCADE
);
